#include <stdexcept>

int main(){
    throw std::runtime_error("");
    return 0;
}